[package]
name = "board_diff"
version = "0.1.0"
authors = ["theRippedPug <tejasshastryumesh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = { git = "https://github.com/jordanbray/chess"}